apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
      strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  partitions: 12
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    cleanup.policy: delete
    min.cleanable.dirty.ratio: 0.5
    preallocate: true

---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: minimal
spec:
  authentication:
    type: tls
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: helloworld-producer
  name: helloworld-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-producer
    spec:
      containers:
      - name: helloworld-producer
        image: strimzi/helloworld-producer:latest
        env:
          - name: CA_CRT
            valueFrom:
              secretKeyRef:
                name: my-cluster-cluster-ca-cert
                key: ca.crt
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9093
          - name: TOPIC
            value: helloworld-test-apps
          - name: TIMER
            value: "1000"
          - name: NUMBER_OF_KEYS
            value: "3"
          - name: EXAMPLE_LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: helloworld-consumer
  name: helloworld-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-consumer
    spec:
      containers:
      - name: helloworld-consumer
        image: strimzi/helloworld-consumer:latest
        env:
          - name: CA_CRT
            valueFrom:
              secretKeyRef:
                name: my-cluster-cluster-ca-cert
                key: ca.crt
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9093
          - name: TOPIC
            value: helloworld-test-apps
          - name: GROUP_ID
            value: my-helloworld-consumer
          - name: EXAMPLE_LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000"
