topic:
  name: avro-sample
  partitions-num: 4
  replication-factor: 2
server:
  port: 9080
spring:
  kafka:
    bootstrap-servers:
      - ${BOOTSTRAP_SERVER}  
    properties:
      # CCloud broker connection parameters
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: OAUTHBEARER
      request.timeout.ms: 20000
      retry.backoff.ms: 500
      sasl.jaas.config: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required; 
      sasl.login.callback.handler.class: io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
      security.protocol: SASL_SSL

      schema.registry.url: ${REGISTRY_URL}  
      #basic.auth.credentials.source: USER_INFO   (4)  
      #schema.registry.basic.auth.user.info: sr_ccloud_key:sr_ccloud_key   (5) 
    #consumer:
    #  group-id: group_id
    #  auto-offset-reset: earliest
    #  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    template:
      default-topic:
logging:
  level:
    root: info
